### ISSUE TITLE
it won't let me do a new installation with docker I get this error

### ISSUE THREAD

**Issue by Retr0-a** [frappe/frappe_docker#847] opened 2022-07-11 18:41 UTC
invalid interpolation format for x-backend-defaults.image: "required variable FRAPPE_VERSION is missing a value: No Frappe version set". You may need to escape any $ with another $

![image](https://user-images.githubusercontent.com/96309748/178335264-626d4f83-9824-4b5e-aff8-e3f346102c04.png)

**Comment by revant** [comment] 2022-07-12 22:38
i can't reproduce this.

make sure environment variables are set by copying example.env

**Comment by central-iatec** [comment] 2022-07-13 01:45
they are on I have updated the latest version of docker and this happens on several servers that I tested

> i can't reproduce this.
> 
> make sure environment variables are set by copying example.env

they are on I have updated the latest version of docker and this happens on several servers that I tested

**Comment by revant** [comment] 2022-07-16 13:32
I'll keep this open. may be someone else can help.

**Comment by central-iatec** [comment] 2022-07-16 14:00
> I'll keep this open. May be someone else can help.

I did a clean installation of erpnext by docker and followed the steps as it is in git copy the env files and more but it tells me that I don't have the frappe_version variable

**Comment by sdfateh** [comment] 2022-08-03 07:15
@Retr0-a Share your env file

**Comment by revant** [comment] 2022-08-04 06:32
check if specifying `--env-file=.env` works for docker compose commands

**Comment by revant** [comment] 2022-08-18 00:05
I'll close this.

open new issue if --env-file doesn't work for you.

**Closed by revant** 2022-08-18 00:05 UTC

**Comment by VGerris** [comment] 2023-01-02 00:43
```
docker compose down --env-file=
unknown flag: --env-file
```

**Comment by revant** [comment] 2023-01-09 07:20
> --env-file=.env

try `--env-file=.env` just after `compose`

```shell
docker compose --env-file=.env down
```

for more help `docker compose --help`

**Comment by Catch0815** [comment] 2023-06-20 17:06
frappe_docker % docker-compose --env-file=example.env up
[+] Running 2/8
 ⠴ queue-short Pulling                                                                                                              5.6s
 ⠴ scheduler Pulling                                                                                                                5.6s
 ⠴ frontend Pulling                                                                                                                 5.6s
 ⠴ backend Pulling                                                                                                                  5.6s
 ✘ configurator Error                                                                                                               5.6s
 ⠴ queue-long Pulling                                                                                                               5.6s
 ⠴ queue-default Pulling                                                                                                            5.6s
 ✘ websocket Error                                                                                                                  5.6s
no matching manifest for linux/arm64/v8 in the manifest list entries

Can anybody help me solving this issue? Is there another one out there with Apple Silicone?

**Comment by saurabh47** [comment] 2023-10-12 16:35
> frappe_docker % docker-compose --env-file=example.env up [+] Running 2/8 ⠴ queue-short Pulling 5.6s ⠴ scheduler Pulling 5.6s ⠴ frontend Pulling 5.6s ⠴ backend Pulling 5.6s ✘ configurator Error 5.6s ⠴ queue-long Pulling 5.6s ⠴ queue-default Pulling 5.6s ✘ websocket Error 5.6s no matching manifest for linux/arm64/v8 in the manifest list entries
> 
> Can anybody help me solving this issue? Is there another one out there with Apple Silicone?

Facing the same issue on the M2 Chip
