### ISSUE TITLE
Developer mode

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#95] opened 2020-03-03 15:21 UTC
Hello,
How is it possible to enable the developer mode in the new frappe_docker?
David

**Comment by revant** [comment] 2020-03-03 23:17
Add key "developer_mode": 1 to site_config.json of specific site or to common_site_config.json

both jsons are available under volume mounted for "sites"

**Comment by revant** [comment] 2020-03-03 23:18
Keep the discussion going

**Comment by ddavidebor** [comment] 2020-03-03 23:26
allright I suggest we keep this issue open until this is properly documented in the readme

**Comment by revant** [comment] 2020-03-03 23:33
Please help us document things.

Because I missed this in the first place! Somethings I may feel not necessary may be necessary!

I've added another issue for docs. if you wish to move it there? #94 

@Thunderbottom is planning to make a gh-pages branch for docs.

**Comment by ddavidebor** [comment] 2020-03-04 00:21
@revant following on my question about development mode, can this new docker images actually be used for development?
Previous docker images for development featured things such as automatic javascript watch/rebuild/reload

**Comment by revant** [comment] 2020-03-04 00:50
I've not used previous image for development.

I'm already committed on some things here as priority. After that I'll check vscode dev containers.

**Comment by chabad360** [comment] 2020-03-04 02:18
Having `"developer_mode": 1` wont help much if we don't have live rebuilding...

**Comment by ddavidebor** [comment] 2020-03-04 23:22
> Having `"developer_mode": 1` wont help much if we don't have live rebuilding...

Do you know how live rebuilding can be activated? 

---
some relevant info bookmarked for the future
https://github.com/frappe/erpnext/wiki/VSCode-Debugging-for-Frappe-Python
https://github.com/frappe/frappe/blob/6763ee7712935d14d222a9177d62158ed5049798/frappe/build.py

**Comment by chabad360** [comment] 2020-03-05 01:30
It's not easy to do by design, but it would basically bloat up the `frappe-assets` image by using the just build phase instead of having a build phase and a "just nginx" phase, then you would have to devise a method to allow the `frappe-assets` container to determine when there are changes to the app, and then trigger a rebuild and copy the files over to where they belong.

**Comment by ddavidebor** [comment] 2020-03-05 10:20
yeah you're right, also such mode would go against docker best practices.
Perhaps best way is simply to give a little bit of a facelift to the old repository so that there is still an easy way to develop

**Comment by revant** [comment] 2020-03-05 11:23
I'm working on getting back the dev container

https://github.com/revant/frappe_docker/tree/feat-dev-docker

No root in container
Nvm so that v11 and v12 can be developed
Python Debugger working

**Comment by ddavidebor** [comment] 2020-03-05 17:07
That's fantastic, please let me know how I can help

**Comment by revant** [comment] 2020-03-05 19:08
https://github.com/frappe/frappe_docker/blob/develop/development/README.md

Try this.

Closing this. Open separate issues of your face any problems

**Closed by revant** 2020-03-05 19:08 UTC
