### ISSUE TITLE
How to deploy from develoment docker

### ISSUE THREAD

**Issue by bhangun** [frappe/frappe_docker#339] opened 2020-08-31 08:05 UTC
Is there any workaround to deploy frappe/ERPNext from docker development mode

I has tried with single/multibench not work well.
All node were running include nginx on port 80, but not cannot acces outside docker instance.

**Comment by revant** [comment] 2020-08-31 14:36
Development image is not built for production run.
It has sudo installed in it, sudo doesn't ask password for development convenience.

Also there is no process manager like supervisor in the image to keeps the processes running.

> I has tried with single/multibench not work well.
All node were running include nginx on port 80, but not cannot acces outside docker instance.

Currently I've 10 sites on kubernetes 
and 6 sites on single node Docker swarm running in production. I am not able to reproduce this.

With docker, traefik, other proxies and docker services available complex infrastructure can be setup,
it is out of scope for Frappe/ERPNext to document all scenarios. Community documents whatever we come across and that builds the documentation.

**Comment by bhangun** [comment] 2020-09-01 10:09
Hi @revant,
Thanks for your respond.

i follow this [custom](https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md) guideline.
And this the [docker-compose](https://gist.github.com/bhangun/898e8da410dc4754e5988d6ac144ec5f) i used for.

from this [custom](https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md) it use port 80 but not expose to external by default. So i added below on the turaerp-assets. 
```
 ports:
      - "80:80"
      - "443:443"
```
all services are running but it doesn't show anything.
![image](https://user-images.githubusercontent.com/124742/91836468-022c2e00-ec75-11ea-8c70-d52d46acdf9c.png)

i've no idea about this. i there any workaround about this. or may be another docker-compose ?
Thanks

**Comment by revant** [comment] 2020-09-02 06:19
Your docker-compose seems to publish port 8000?

I'm really not able to reproduce this.

I've custom app running.

docs.erpnext.com is custom app running on kubernetes.

**Comment by revant** [comment] 2020-09-04 23:22
Re open is necessary

**Closed by revant** 2020-09-04 23:22 UTC
Labels: question

**Comment by bhangun** [comment] 2020-09-07 04:33
hi revant,
ok it doesn't matter if this issue is closed.
> Your docker-compose seems to publish port 8000?
No, you mean on turaerp-assets? i used port 80.
and turaerp-python (turaerp--worker) it use default port 8000
as u see on this
> ![image](https://user-images.githubusercontent.com/124742/91836468-022c2e00-ec75-11ea-8c70-d52d46acdf9c.png)

BTW, 
on turaerp-assets as the frontend (CMIIW) the logs are below:
`Waiting for frappe-python to be available on turaerp-python port 8000
Waiting for frappe-python to be available on turaerp-python port 8000
Frappe-python available on turaerp-python port 8000
Waiting for frappe-socketio to be available on frappe-socketio port 9000
Frappe-socketio available on frappe-socketio port 9000
2020/09/07 03:39:18 [error] 31#31: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: $http_host, request: "GET / HTTP/1.1", upstream: "http://172.20.0.2:8000/", host: "localhost"
127.0.0.1 - - [07/Sep/2020:03:39:18 +0000] "GET / HTTP/1.1" 502 5444 "-" "curl/7.64.0" "-"`

any idea of this?
Thanks

**Comment by revant** [comment] 2020-09-08 06:40
what is the site name that you used to create first site?

Try accessing it using that sitename?

also in case of old multi bench setup, directly publish port 80 of -nginx container. no need for python to publish port.

**Comment by revant** [comment] 2020-09-09 06:04
Btw if you're doing development use frappe/bench Docker image

Refer https://github.com/frappe/frappe_docker/tree/develop/development

**Comment by bhangun** [comment] 2020-09-09 08:57
Yes you are correct.  For my previous problem it just domain name/site
name. Because all services were running.
So the site has been accessed and success with the  site name i was defined
before erp.tura.tech.

Why i was always failed to access the site before?

It just my stupid, evidently the browser were default to used HTTPS, but
i'm not set properly the SSL, so itu should accessed with HTTP and success.

But then i found another issue.
Which is erpnext is not what i was customized. May be i'm not mapping
properly. I still found the cause.

**Comment by rakeshyannamani** [comment] 2020-09-09 09:42
@rmehta i am trying to build and deploy ERPNext on docker
i'm having issues ref below - i have tried verious options like below

1. using env-local & env-porduction
2. chnaging the Port in docker-compose.yml (8080:80 as i have another service running on the 80)

could you please advise what am i missing ?

![image](https://user-images.githubusercontent.com/6128116/92582211-4be8ca00-f2ae-11ea-8779-a10bf376653b.png)

**Comment by revant** [comment] 2020-09-09 16:28
> chnaging the Port in docker-compose.yml (8080:80 as i have another service running on the 80)

You cannot use any other port by just changing the `ports:` section.

for development use the `frappe/bench:latest` image and refer related docs. https://github.com/frappe/frappe_docker/blob/develop/development

for building custom images refer https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md

related post https://discuss.erpnext.com/t/docker-setup-with-different-https-port/63202

**Comment by rakeshyannamani** [comment] 2020-09-09 18:31
@revant Thanks i have tried your latest method of Docker Production and struck at this "scheduler is disabled" and it kicked me out of the process am i missing anything

![image](https://user-images.githubusercontent.com/6128116/92638432-e3263f80-f2f7-11ea-9ee3-727404768f08.png)

**Comment by revant** [comment] 2020-09-10 05:05
I think you're manually executing command from container? If you use the entrypoint the base directory to execute all commands is /home/frappe/frappe-bench/sites

**Comment by rakeshyannamani** [comment] 2020-09-10 19:28
@revant 
I have followed exactly what this link says https://github.com/frappe/bench#easy-install-script (ref below) 
![image](https://user-images.githubusercontent.com/6128116/92790170-2ac8cc00-f3c9-11ea-814f-e8d2614218b9.png)
**1st Command**
![image](https://user-images.githubusercontent.com/6128116/92789910-eb9a7b00-f3c8-11ea-9bce-ee86faae8308.png)
**2nd Command**
![image](https://user-images.githubusercontent.com/6128116/92790011-02d96880-f3c9-11ea-8a45-124e310a2429.png)
Same error as prior, then i used docker exec to enter into the container bash (ref below)
![image](https://user-images.githubusercontent.com/6128116/92790068-108eee00-f3c9-11ea-80af-a171480666d7.png)

please advise if i have done something wrong 👍

**Comment by revant** [comment] 2020-09-10 23:45
Try running the commands as non root user from docker group instead of root user?
